### ISSUE TITLE
失联确认

### ISSUE THREAD

**Issue by dou4cc** [JimmyJichi/youtube-subs-counter#1]

**Comment by jichizhang** [comment]
我的所有推特帳號，包括 @jichi_zhang，@jichi_en，@jimmy_strangers，都被推特封鎖了。目前正在上訴中，如果要聯繫我可以使用 Telegram。

**Comment by dou4cc** [comment]
Telegram 我刚刚弃用. Telegram 其实比 Twitter 还恶心.

**Comment by dou4cc** [comment]
> 都被推特封鎖了

你还有 JimmyLikeBot 和 JichiZhangJimmy.
